app/sections/forms.py
from flask_wtf import FlaskForm
from flask_babel import _, lazy_gettext as _l
from wtforms.validators import ValidationError, DataRequired
from app.models import Sections
from wtforms import TextField, BooleanField, SubmitField


class SectionForm(FlaskForm):
    name = TextField(label = _l("Page name"), validators =[DataRequired()])
    is_displayed =  BooleanField(_l('Display'))
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_name, *args, **kwargs):
        super(SectionForm, self).__init__(*args, **kwargs)
        self.original_name = original_name

    def validate_name(self, name):
        if name.data != self.original_name:
            section = Sections.query.filter_by(name=self.name.data).first()
            if section is not None:
                raise ValidationError(_l('Please use a different section name.'))

class PageForm(FlaskForm):
    submit = SubmitField(_l('Submit'))

app/sections/__init__.py
from flask import Blueprint

bp = Blueprint('sections', __name__, template_folder='templates')

from app.sections import routes

app/sections/routes.py
# Здесь добавлены все функции, связанные с созданием, редактированием и удалением секций и шаблонов к ним

from app import db
from app.sections import bp
from app.sections.forms import *
from app.models import *
from app.dynamic_fields.dynamic_fields import *
from app.dynamic_fields.forms import *
from app.routes import roles_required

from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from flask_babel import _, lazy_gettext as _l
from werkzeug.urls import url_parse


# Раздел, где будут отображаться все документы
@bp.route('/all_documents',methods=['GET', 'POST'])
@login_required
def all_documents():
    media = Media.query.all()
    files = []
    for field in media:
        if field.file:
            files.append(field.file)
    return render_template("all_documents.html", files = files)


#---------------------------------------------------------------------
#                           Sections
#---------------------------------------------------------------------

def create_or_edit_section(section, is_edit):
    form = SectionForm(section.name)
    add_field_form = AddFieldForm()

    is_validated, dynamic_forms = dynamic_fields(section, section.fields, True)

    if request.method == "GET":
        form.name.data = section.name
        form.is_displayed.data = section.display


    elif is_validated and form.validate_on_submit():
        section.name = form.name.data
        section.display = form.is_displayed.data
        if not is_edit:
            db.session.add(section)
        db.session.commit()
        return redirect(url_for('sections.view_section', section_id=section.id))


    return render_template("create_or_edit_section.html", add_field_form = add_field_form, 
        form = form, is_template = True, dynamic_forms = dynamic_forms)

@bp.route('/create_section',methods=['GET', 'POST'])
@roles_required(['Admin'])
def create_section():
    section = Sections()
    return create_or_edit_section(section, False)

@bp.route('/edit_section/<section_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def edit_section(section_id):
    section = Sections.query.filter_by(id = section_id).first()
    return create_or_edit_section(section, True)

@bp.route('/delete_section/<section_id>')
@roles_required(['Admin'])
def delete_section(section_id):
    section = Sections.query.filter_by(id = section_id).first()
    if section.pages:
        for page in section.pages:
            _delete_page(page.id)
            db.session.commit()
    delete_fields(section.fields)
    db.session.commit()
    db.session.delete(section)
    db.session.commit()

    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('sections.main')
    return redirect(next_page)


@bp.route('/sections/<section_id>', methods=['GET'])
@roles_required(['Admin'])
def view_section(section_id):
    section = Sections.query.filter_by(id = section_id).first()
    return render_template("section_pages.html", title = section.name,
        pages = section.pages, section_id = section_id)


#---------------------------------------------------------------------
#                           Pages
#---------------------------------------------------------------------

def create_or_edit_page(page, fields, section, is_edit):
    form = PageForm()
    is_validated, dynamic_forms = dynamic_fields(page, fields, False)
    if is_validated and form.validate_on_submit():
        page.section = section
        if not is_edit:
            db.session.add(page)
        db.session.commit()
        return redirect(url_for("sections.view_section", section_id = section.id))
    return render_template("create_or_edit_page.html", is_template = False, form = form,
         dynamic_forms = dynamic_forms)

@bp.route('/create_page/<section_id>',methods=['GET', 'POST'])
@roles_required(['Admin'])
def create_page(section_id):
    page = Pages()
    section = Sections.query.filter_by(id = section_id).first()
    fields = section.fields
    return create_or_edit_page(page,fields, section, False)

@bp.route('/edit_page/<page_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def edit_page(page_id):
    page = Pages.query.filter_by(id = page_id).first()
    return create_or_edit_page(page, page.fields, page.section , True)

def _delete_page(page_id):
    page = Pages.query.filter_by(id = page_id).first()
    delete_fields(page.fields)
    db.session.commit()
    db.session.delete(page)
    db.session.commit()

@bp.route('/delete_page/<page_id>')
@roles_required(['Admin'])
def delete_page(page_id):
    _delete_page(page_id)
    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('sections.main')
    return redirect(next_page)

#Отображение всей информации о странице 
@bp.route('/view_full_page/<page_id>', methods=['GET'])
@roles_required(['Admin'])
def full_page(page_id):
    page = Pages.query.filter_by(id = page_id).first()
    return render_template("full_page.html",page = page)



# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------

@bp.route('/main', methods=['GET', 'POST'])
@login_required
def main():
    return render_template("main.html", title = _l("Main page"),
        sections = Sections.query.all())

# Глобальная функция, нужна для отображения списка секций в панели 
def get_sections():
    return Sections.query.all() 

app.jinja_env.globals.update(get_sections = get_sections)

app/sections/templates/all_documents.html
{% extends "base.html" %}

{% block content %}
	{% for file in files %}
	<table width="500">

		<tr>
			<td>
					<a href="{{ url_for('download_file', filename = file.encrypted_filename) }}">{{ file.filename }}</a>
			</td>
			<td>
					<p>File type: {{file.file_type}}</p>
			</td>
		</tr>
	</table>

	{% endfor %}
{% endblock %}

app/sections/templates/create_or_edit_page.html
{% extends "base.html" %}
{% block content %}

	<form method="post" enctype="multipart/form-data">
		{{ form.hidden_tag() }} 
		
		{% include "fields_render.html" %}		
		
		{{ form.submit }}
		{% for error in form.errors %}
			<span style="color: red;">[{{ error }}]</span>
  		{% endfor %}
     </form>
	 
{% endblock %}

app/sections/templates/create_or_edit_section.html
{% extends "base.html" %}
{% block content %}

	{% include "templates_dynamic_fields.html" %}

	<form method="post">
		{{ form.hidden_tag() }}
		<p>{{add_field_form.fields_list.label}}: {{add_field_form.fields_list()}}</p>
		<button id="add_field" type="button">{{_('Add field')}}</button>
		
		{% for error in add_field_form.errors %}
					<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
	</form>
	
     <form method="post" enctype="multipart/form-data">
		{{ form.hidden_tag() }} 
        <p>{{_('Display section')}} {{ form.is_displayed }}</p>
		<p>{{_('Section name')}} {{ form.name }}</p>
		
        {% include "fields_render.html" %}

	   <p>{{ form.submit() }}</p>
	   {% for error in form.name.errors %}
	  		<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
     </form>
	 
{% endblock %}

app/sections/templates/full_page.html
{% extends "base.html" %}
{% block content %}
	{% from "fields_show.html" import show_fields %}
	{{ show_fields(page.fields, True) }}
{% endblock %}

app/sections/templates/main.html
{% extends "base.html" %}

{% block content %}
    <table>
		{% for section in sections %}
			{% if section.display %}
				<tr>
					<td>
						<a href="{{ url_for('sections.view_section', section_id=section.id) }}">{{ section.name }}</a>
					</td>
				</tr>
			{% endif %}
		{% endfor %}
	</table>

{% endblock %}

app/sections/templates/page.html
{% from "fields_show.html" import show_fields %}
{{ show_fields(page.fields) }}

<div class="task_info">

	<div class="user_edit">
		<div class="edit">
				<a href="{{ url_for('sections.full_page', page_id=page.id) }}">{{ _('View')}}</a>
		</div>
		{% if current_user.roles[0].name == "Admin" %}
			<div class="edit">
					<a href="{{ url_for('sections.edit_page', page_id=page.id) }}">{{ _('Edit')}}</a>
			</div>
			<div class="delete">
					<a href="{{ url_for('sections.delete_page', page_id=page.id, next = request.path) }}">{{ _('Delete page')}}</a>	
			</div>
		{% endif %}  
	</div>

</div>

app/sections/templates/section_pages.html
{% extends "base.html" %}

{% block content %}

<div class="task_info">

	<div class="user_edit">
		<div class="edit">
				<a href="{{ url_for('sections.create_page', section_id=section_id) }}">{{ _('Create new page')}}</a>
		</div> 
	</div>
</div>      


    {% for page in pages %}
    		{% include 'page.html' %}
    		<br>
    {% endfor %}

{% endblock %}