app/tasks/forms.py
from flask_babel import _, lazy_gettext as _l
from flask_wtf import FlaskForm
from app.models import Users, Roles
from wtforms import TextField, SubmitField, SelectField
from wtforms_sqlalchemy.fields import QuerySelectField
from sqlalchemy import or_
from flask_login import current_user


def assigners_query():
    return Users.query.join(Users.roles).filter(or_(Roles.name == "Admin", 
        Roles.name == "Usual"), ~Users.roles.any(Roles.name == "God"))

def get_pk(obj):
    return str(obj)

def acceptors_query():
    return Users.query.join(Users.roles).filter(or_(Roles.name == "Client", 
        Roles.name == "Usual"), ~Users.roles.any(Roles.name == "God"), Users.id != current_user.id)

class TaskForm_edit(FlaskForm):
    assigner = QuerySelectField(_l('Assigner'), query_factory=assigners_query, 
        get_pk = get_pk, get_label = "email")
    acceptor = QuerySelectField(_l('Acceptor'), query_factory=acceptors_query, 
        get_pk = get_pk, get_label = "email")
    status = SelectField(_l('Status'), 
        choices=[('Issued',_l('Issued')),('In progress',_l('In progress')),('Done',_l('Done'))])
    submit = SubmitField(_l('Submit'))

class TaskForm_create(FlaskForm):
    acceptor = QuerySelectField(_l('Acceptor'), query_factory=acceptors_query, 
        get_pk = get_pk, get_label ="email")
    submit = SubmitField(_l('Submit'))

class TemplateForm(FlaskForm):
    name = TextField(label = _l("Template name"))
    submit = SubmitField(_l('Submit'))

app/tasks/__init__.py
from flask import Blueprint

bp = Blueprint('tasks', __name__, template_folder='templates')

from app.tasks import routes

app/tasks/routes.py
# Здесь добавлены все функции, связанные с созданиемб редактированием и удалением заданий и шаблонов к ним

from flask import render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_required
from flask_babel import _, lazy_gettext as _l
from werkzeug.urls import url_parse

from app import db
from app.tasks import bp
from app.tasks.forms import *
from app.models import *
from app.dynamic_fields.dynamic_fields import *
from app.dynamic_fields.forms import AddFieldForm
from app.routes import roles_required


#_____________________________________________
#      Task_templates - Шаблоны заданий
#---------------------------------------------

def process_template(template, is_edit):
    form = TemplateForm()
    add_field_form = AddFieldForm()
    
    is_validated, dynamic_forms = dynamic_fields(template, template.fields, True)

    if request.method == 'GET':
        #Заполняем поля при отображении страницы
        form.name.data = template.name
        
    elif is_validated and form.validate_on_submit():
        # Сохраняем данные в БД
        template.name = form.name.data
        if not is_edit:        
            db.session.add(template) 
        db.session.commit()
        return redirect(url_for('tasks.task_templates'))

    return render_template("create_or_edit_task_template.html", add_field_form = add_field_form,
        form = form, is_template = True, dynamic_forms = dynamic_forms)

# Создание шаблона
@bp.route('/create_task_template', methods=['GET', 'POST'])
@roles_required(['Admin'])
def create_task_template():
    template = Task_templates()
    return process_template(template, False)


@bp.route('/edit_task_template/<template_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def edit_task_template(template_id):
    template = Task_templates.query.filter_by(id = template_id).first()
    return process_template(template, True)


@bp.route('/delete_task_template/<template_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def delete_task_template(template_id):
    template = Task_templates.query.filter_by(id = template_id).first()
    delete_fields(template.fields)
    db.session.commit()
    db.session.delete(template)
    db.session.commit()
    return redirect(url_for("tasks.task_templates"))


#_____________________________________________
#            Tasks - Задания
#---------------------------------------------

def process_task(form, task, fields, is_edit):
    #Формы для разных типов полей

    is_validated, dynamic_forms = dynamic_fields(task, fields, False)

    if request.method == 'GET' and is_edit:
        #Заполняем поля при отображении страницы
        form.status.data = task.status
        form.assigner.data = task.assigner
        form.acceptor.data = task.acceptor
 
    elif is_validated and form.validate_on_submit():
        if is_edit:
            assigner = form.assigner.data
        else:
            assigner = current_user

        task.assigner = assigner
        task.acceptor = form.acceptor.data

        if is_edit:
            task.status = form.status.data

        if not is_edit:
            db.session.add(task)    
        db.session.commit()
        flash(_l('Your changes have been saved.'))
        return redirect(url_for('auth.login'))
    
    return render_template("create_or_edit_task.html", form = form, 
        is_edit = is_edit, dynamic_forms = dynamic_forms, is_template = False)


@bp.route('/create_task/<template_id>', methods=['GET', 'POST'])
@roles_required(['Admin', 'Usual'])
def create_task(template_id):
    task = Tasks()
    fields = Task_templates.query.filter_by(id = template_id).first().fields
    form = TaskForm_create()

    return process_task(form, task, fields, False)

    
@bp.route('/edit_task/<task_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def edit_task(task_id):
    task = Tasks.query.filter_by(id = task_id).first()
    form = TaskForm_edit()
    return process_task(form, task, task.fields, True)


@bp.route('/delete_task/<task_id>')
@roles_required(['Admin'])
def delete_task(task_id):
    task = Tasks.query.filter(Tasks.id == task_id).first()
    delete_fields(task.fields)
    db.session.commit()
    db.session.delete(task)
    db.session.commit()
    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('users.all_users')
    return redirect(next_page)



#_____________________________________________
#      Отображение заданий на страницах
#---------------------------------------------

@bp.route('/all_tasks', methods=['GET', 'POST'])
@roles_required(['Admin'])
def all_tasks():
    return render_template("tasks.html", title = _l("All tasks"),
        tasks = Tasks.query.order_by(Tasks.timestamp.desc()).all())


# Страница с выбором существующего шаблона задания или создание нового шаблона (создание только для админа)
@bp.route('/task_templates', methods=['GET', 'POST'])
@roles_required(['Admin', 'Usual'])
def task_templates():
    templates = Task_templates.query.all()
    return render_template('task_templates.html', templates = templates)


@bp.route('/issued_tasks', methods=['GET', 'POST'])
@roles_required(['Admin', 'Usual'])
def issued_tasks():
    tasks = current_user.assign.order_by(Tasks.timestamp.desc()).all()
    return render_template("tasks.html", title=_l('Issued tasks'), tasks = tasks)


@bp.route('/your_tasks', methods=['GET', 'POST'])
@login_required
def your_tasks():
    tasks = current_user.accept.order_by(Tasks.timestamp.desc()).all()
    return render_template("tasks.html", title=_l('My tasks'), tasks = tasks)

app/tasks/templates/_task.html
{% from "fields_show.html" import show_fields %}
{{ show_fields(task.fields) }}

<div class="task_info">

		<div class="avatar">
				<img src="{{ task.assigner.avatar() }}">
		</div>
		
		<div class="user_name">
				<a href="{{ url_for('users.user', id=task.assigner.id) }}">{{ task.assigner.email }}</a> | {{ _('Assigned to:')}} <a href="{{ url_for('users.user', id=task.acceptor.id) }}">{{ task.acceptor.email }}</a>
		</div>
		
		<div class="task_status">
				<div class="label">
						{{ _('Status:')}}
				</div>
				<div class="info">
						{{ _(task.status)}}
				</div>
		</div>

		<div class="task_issuid_time">
				<div class="label">
						{{ _('Issued time:')}}
				</div>
				<div class="info">
						{{ task.timestamp.strftime('%d %B %Y at %H:%M') }}
				</div>
		</div>
							
		<div class="user_edit">
				{% if current_user.roles[0].name == "Admin" %}
				<div class="edit">
						<a href="{{ url_for('tasks.edit_task', task_id=task.id) }}">{{ _('Edit')}}</a>
				</div>
				<div class="delete">
						<a href="{{ url_for('tasks.delete_task', task_id=task.id, next = request.path) }}">{{ _('Delete task')}}</a>	
				</div>
				{% endif %}  
		</div>

</div>

app/tasks/templates/create_or_edit_task.html
{% extends "base.html" %}

{% block content %}
<div id="create_task">
	<form method="post" enctype="multipart/form-data">
		{{ form.hidden_tag() }} 

		<div class="line">	
			{% if is_edit %}
					<div class="assigner">
							<div class="label">
									{{ form.assigner.label }}:
							</div>
							<div class="info">
									{{ form.assigner() }}
							</div>
					</div>
					<div class="acceptor">
							<div class="label">
									{{ form.acceptor.label }}:
							</div>
							<div class="info">
									{{ form.acceptor() }}
							</div>
					</div>
					<div class="status">
							<div class="label">
									{{ form.status.label }}:
							</div>
							<div class="info">
									{{ form.status() }}
							</div>
					</div>
			{% else %}
					<div class="acceptor">
							<div class="label">
									{{ form.acceptor.label }}:
							</div>
							<div class="info">
									{{ form.acceptor() }}
							</div>
					</div>
			{% endif %}
		</div>

		
	{% include "fields_render.html" %}

	<p>{{ form.submit() }}</p>
	{% for error in form.errors %}
			<span style="color: red;">[{{ error }}]</span>
	{% endfor %}
	</form>
</div>
{% endblock %}

app/tasks/templates/create_or_edit_task_template.html
{% extends "base.html" %}

{% block content %}

	{% include "templates_dynamic_fields.html" %}

	<form method="post">
		{{ form.hidden_tag() }}
		<p>{{add_field_form.fields_list.label}}: {{add_field_form.fields_list()}}</p>
		<button id="add_field" type="button">{{_('Add field')}}</button>
		
		{% for error in add_field_form.errors %}
					<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
	</form>
	
     <form method="post" enctype="multipart/form-data">
		{{ form.hidden_tag() }} 
		
		<p>{{ form.name.label }}: {{ form.name() }}</p>
		
		{% include "fields_render.html" %}

	   <p>{{ form.submit() }}</p>
	   {% for error in form.errors %}
	  		<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
     </form>
	 
{% endblock %}

app/tasks/templates/task_templates.html
{% extends "base.html" %}

{% block content %}
<div id="templates">
    
		<h3> {{ _('Choose type of task')}} </h3>
		{% for template in templates %}
			
			<div class="templates_line">
					<div class="template_create">
							<a href="{{ url_for('tasks.create_task', template_id = template.id) }}">
										{% if template.name %}
											{{ template.name }}
										{% else %}
											{{_('Template')}}_{{loop.index}}
										{% endif %}
							</a>
					</div>
					{% if current_user.roles[0].name == "Admin" %}
					<div class="template_edit">
							<a href="{{ url_for('tasks.edit_task_template', template_id = template.id) }}">{{ _('Edit template')}}</a>	
					</div>
					<div class="template_delete">
							<a  href="{{ url_for('tasks.delete_task_template', template_id = template.id) }}">{{ _('Delete template')}}</a>	
					</div>
					{% endif %}
			</div>
			
		{% endfor %}	
		
		{% if current_user.roles[0].name == "Admin" %}
			<div class="template_new">
					<a href="{{ url_for('tasks.create_task_template') }}">	{{ _('New template')}}</a>
			</div>
		{% endif %}
	
</div>
{% endblock %}

app/tasks/templates/tasks.html
{% extends "base.html" %}

{% block content %}
      
    {% for task in tasks %}
    		{% include '_task.html' %}
    		<br>
    {% endfor %}

{% endblock %}