app/users/forms.py
from flask_babel import _, lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError, DataRequired, Email
from app.models import Users
from wtforms import Form, StringField, SubmitField, SelectField
from flask_wtf.file import FileField, FileAllowed

class EditProfileForm_Admin(FlaskForm):
    email = StringField(_l('Email'), validators=[DataRequired(), Email()])
    role_list = SelectField(_l('Role'), 
        choices=[('Admin',_l('Admin')),('Usual',_l('Usual user')),('Not confirmed',_l('Not confirmed'))])
    picture = FileField(_l('Update Profile Picture'), validators=[FileAllowed(['jpg', 'png','jpeg'])])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_email, *args, **kwargs):
        super(EditProfileForm_Admin, self).__init__(*args, **kwargs)
        self.original_email = original_email

    def validate_email(self, email):
        if email.data != self.original_email:
            user = Users.query.filter_by(email=self.email.data).first()
            if user is not None:
                raise ValidationError(_l('Please use a different email.'))


class EditProfileForm(FlaskForm):
    picture = FileField(_l('Update Profile Picture'), validators=[FileAllowed(['jpg', 'png','jpeg'])])
    submit = SubmitField(_l('Submit'))

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__, template_folder='templates')

from app.users import routes

app/users/routes.py
from flask_babel import _, lazy_gettext as _l
from flask import render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_required
from flask import abort

from werkzeug.urls import url_parse
from sqlalchemy import or_
import os
from PIL import Image
from flask_wtf import FlaskForm

from app.routes import roles_required

from app import app, db
from app.users import bp
from app.users.forms import *
from app.models import *



# Главная страница пользователя, с заданиями, которые он выдал
@bp.route('/user/<id>', methods=['GET', 'POST'])
@login_required
def user(id):
    user = Users.query.filter_by(id=id).first_or_404()
    user_roles = [role.name for role in user.roles]
    if "God" in user_roles and current_user.id != user.id:
        return abort(404)
    tasks = Tasks.query.filter(or_(Tasks.assigner_id == user.id, 
        Tasks.acceptor_id == user.id)).order_by(Tasks.timestamp.desc()).all()
    return render_template('user.html', title = user.last_name+" "+ user.first_name, 
        user=user, tasks = tasks)


@bp.route('/all_users', methods=['GET', 'POST'])
@roles_required(['Admin'])
def all_users():
    all_users = Users.query.filter(Users.id!=current_user.id, ~Users.roles.any(Roles.name == "God")).all()
    return render_template("all_users.html", title = _l("All users"), users = all_users)


def save_avatar(user, picture):
    if picture:
        __ , encrypted_filename = encode_filename(picture.filename)
        image = Image.open(picture)
        image.save(os.path.join(app.root_path, 'static/avatars/', encrypted_filename))
        user.avatar_path = encrypted_filename


@bp.route('/edit_user/<id>', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    is_admin = (current_user.roles[0].name == "Admin")
    user = Users.query.filter_by(id=id).first()
    
    if not is_admin and current_user.id != user.id:
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('users.all_users')
        return redirect(next_page)

    if is_admin:
        form = EditProfileForm_Admin(user.email)
    else:
        form = EditProfileForm()

    if user.profile:
        profile = user.profile
        fields = profile.fields
    else:
        profile = Profiles()

        profile_template = Profile_template.query.filter_by(id=1).first()
        fields = []
        if profile_template:
            fields = profile_template.fields

    is_validated, dynamic_forms = dynamic_fields(profile, fields, True)

    if request.method == 'GET' and is_admin:
        # Предзаполнение полей
        form.email.data = user.email
        form.role_list.data = user.roles[0].name

    elif is_validated and form.validate_on_submit():
        save_avatar(user, form.picture.data)
        if is_admin:
            user.email = form.email.data
            user.roles[0].name = form.role_list.data
            
        if not user.profile:
            user.profile = profile
            db.session.add(profile)
        db.session.commit()
        flash(_l('Your changes have been saved.'))
        return redirect(url_for("users.all_users"))

    
    return render_template('edit_user.html', title=_l('Edit Profile'),
        form=form, user = user, is_template = False, dynamic_forms = dynamic_forms)


# --- Удаление пользователя и заданий ----
@bp.route('/delete_user/<user_id>')
@roles_required(['Admin'])
def delete_user(user_id):
    user = Users.query.filter_by(id=user_id).first()

    # Удаление аватарки
    if user.avatar_path:
        os.remove(os.path.join(app.root_path, 'static/avatars/', user.avatar_path))

    # #Удаления информации о профиле
    if user.profile:
        if user.profile.fields:
            delete_fields(user.profile.fields)
        db.session.delete(user.profile)
        
    db.session.commit()

    #Удаление всех заданий, связанных с этим пользователем
    acceptor_tasks = Tasks.query.filter(Tasks.acceptor_id == user.id).all()
    assigner_tasks = Tasks.query.filter(Tasks.assigner_id == user.id).all()
    for task in acceptor_tasks:
        delete_task(task.id)
    for task in assigner_tasks:
        delete_task(task.id)

    db.session.commit()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("users.all_users"))

@bp.route('/confirm_user/<id>')
@roles_required(['Admin'])
def confirm_user(id):
    user = Users.query.filter_by(id=id).first()
    user.roles[0].name = "Usual"
    db.session.commit()
    return redirect(url_for("users.all_users"))


@bp.route('/profile_template',methods=['GET', 'POST'])
@roles_required(['Admin'])
def profile_template():

    class TemplateProfileForm(FlaskForm):
        submit = SubmitField(_l('Submit'))

    template = Profile_template.query.filter_by(id=1).first()
    if template==None:
        template = Profile_template(id = 1)
        db.session.add(template)

    form = TemplateProfileForm()
    add_field_form = AddFieldForm()
    
    is_validated, dynamic_forms = dynamic_fields(template, template.fields, True)

    if is_validated:
        profiles = Profiles.query.all()
        for profile in profiles:
            delete_fields(profile.fields)
        db.session.commit()
        Profiles.query.delete()
        db.session.commit()
        return redirect(url_for("toolbar_settings"))


    return render_template("profile_template.html", add_field_form = add_field_form, 
        form = form, is_template = True, dynamic_forms = dynamic_forms)

# delete_task нужен в delete_user
from app.tasks.routes import delete_task
from app.dynamic_fields.dynamic_fields import *

app/users/templates/all_users.html
{% extends "base.html" %}

{% block content %}

	{% for user in users %}
	
			<div id="user">
		
				<div class="avatar">
						<img src="{{ user.avatar() }}">
				</div>
				
				<div class="user_info">
				
						<div class="real_name">
								<div class="label">
										{{_("Full name")}}:
								</div>
								<div class="info">
										{{user.last_name}} {{user.first_name}}
								</div>
						</div>
				
						<div class="user_name">
								<div class="label">
										{{_('Email')}}:
								</div>
								<div class="info">
										<a href="{{ url_for('users.user', id=user.id) }}">{{ user.email }}</a>
								</div>
						</div>
						
						{% if user.roles %}
							<div class="user_role">
									<div class="label">
											{{ _('Role')}}:
									</div>
									<div class="info">
											{{_(user.roles[0].name)}}
									</div>
							</div>	
						{% endif %}
						{% if user.roles[0].name == 'Not confirmed' %}
						<div class="user_edit">
							<div class="edit">
									<a href="{{ url_for('users.confirm_user', id=user.id) }}">{{ _('Confirm')}}</a>
							</div>	
						</div>
						{% else %}
							<div class="user_edit">
									<div class="edit">
											<a href="{{ url_for('users.edit_user', id=user.id) }}">{{ _('Edit')}}</a>
									</div>
									<div class="delete">
											<a href="{{ url_for('users.delete_user', user_id=user.id) }}">{{ _('Delete user')}}</a>
									</div>
							</div>
						{% endif %}
				
				</div>				
			
			</div>
			

		
	{% endfor %}

    
{% endblock %}

app/users/templates/edit_user.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('Edit Profile') }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        
        <p>
         	<img src="{{ user.avatar() }}" width="128" height="128">
        </p> 
        
        <p>
		     <b>{{ form.picture.label() }}</b>: 
		     {{ form.picture() }}
		     {% if form.picture.errors %}
				  <p>
		            {% for error in form.picture.errors %}
		                 <span style="color: red;">{{ error }}</span></br>
		            {% endfor %}
		        </p>
           {% endif %}
        </p>
        {% if current_user.roles and current_user.roles[0].name == "Admin" %}
		     <p>
		         <b>{{ form.email.label }}</b>: {{ form.email(size=32) }}<br>
		         {% for error in form.email.errors %}
		         <span style="color: red;">[{{ error }}]</span>
		         {% endfor %}
		     </p>
		     <p>
		         <b>{{ form.role_list.label }}</b>: {{ form.role_list() }} <br>
		         {% for error in form.role_list.errors %}
		         <span style="color: red;">[{{ error }}]</span>
		         {% endfor %}
		     </p>		  
		{% endif %}
		
		{% include "fields_render.html" %}

        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/users/templates/profile_template.html
{% extends "base.html" %}
{% block content %}

	{% include "templates_dynamic_fields.html" %}

	<form method="post">
		{{ form.hidden_tag() }}
		<p>{{add_field_form.fields_list.label}}: {{add_field_form.fields_list()}}</p>
		<button id="add_field" type="button">{{_('Add field')}}</button>
		
		{% for error in add_field_form.errors %}
					<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
	</form>
	
     <form method="post" enctype="multipart/form-data">
		{{ form.hidden_tag() }} 
		
		{% include "fields_render.html" %}

	   <p>{{ form.submit() }}</p>
	   {% for error in form.errors %}
	  		<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
     </form>
	 
{% endblock %}

app/users/templates/user.html
{% extends "base.html" %}

{% block content %}
		
		<div id="user">
		
				<div class="avatar">
						<img src="{{ user.avatar() }}">
				</div>
				
				<div class="user_info">
				
						<div class="real_name">
								<div class="label">
										{{_('Full name')}}:
								</div>
								<div class="info">
										{{current_user.last_name}} {{current_user.first_name}}
								</div>
						</div>
				
						<div class="user_name">
								<div class="label">
										{{_('Email')}}:
								</div>
								<div class="info">
										{{ user.email }}
								</div>
						</div>

						{% if user.roles %}
							<div class="user_role">
									<div class="label">
											{{ _('Role')}}:
									</div>
									<div class="info">
											{{_(user.roles[0].name)}}
									</div>
							</div>
						{% endif %}
						
						
						{% if user.last_seen %}
						<div class="last_session">
								<div class="label">
										{{ _('Last seen on')}}:
								</div>
								<div class="info">
										{{ moment(user.last_seen).format('LLL') }}
								</div>
						</div>
						{% endif %}
						
				</div>
		
		</div>
		{% if user.roles %}
			<div class="user_edit">
				<div class="edit">
						<a href="{{ url_for('users.edit_user', id=user.id) }}">{{ _('Edit')}}</a>
				</div>
				{% if current_user.roles[0].name == "Admin" %}
					<div class="delete">
							<a href="{{ url_for('users.delete_user', user_id=user.id) }}">{{ _('Delete user')}}</a>
					</div>
				{% endif %}
			</div>
		
			<div class="tasks">
				{% if current_user.roles[0].name == "Admin" %}
						<h3> {{ _('All tasks related with that user')}} </h3>
						{% for task in tasks %}
								{% include '_task.html' %}
						{% endfor %}
				{% endif %}
			</div>
		{% endif %}
    
{% endblock %}