app/dynamic_fields/forms.py
from flask_babel import _, lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError, DataRequired, Length
from wtforms import Form, TextField, TextAreaField, IntegerField, \
    FieldList, FormField, HiddenField, BooleanField, SelectField, SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.fields.html5 import DateField

# Форма для кнопки добавления поля
class AddFieldForm(FlaskForm):
    fields_list = SelectField(_l('Field type'), 
        choices=[('Text',_l('Text')), ('TextArea',_l('TextArea')),
            ('Date',_l('Date')),('File',_l('File')),('Picture',_l('Picture')),('Link',_l('Link')),
            ('Number',_l('Number')), ('Categories',_l('Categories')) ])


# Это основная форма, от которой все наследуются
class FieldForm(Form):
    label_ = TextField(label = _l("Label"),validators=[Length(max=50)])
    is_displayed =  BooleanField(_l('Display'))
    order = HiddenField()


# text form
class ExtTextField(FieldForm):
    text = TextField()

class TextsForm(FlaskForm):
    text_fields = FieldList(
        FormField(ExtTextField)
    )


# text area form
class ExtTextAreaField(FieldForm):
    textArea = TextAreaField()

class TextAreasForm(FlaskForm):
    textArea_fields = FieldList(
        FormField(ExtTextAreaField)
    )


# date form
class ExtDateField(FieldForm):
    date = DateField()

class DatesForm(FlaskForm):
    date_fields = FieldList(
        FormField(ExtDateField)
    )


# link form
class LinkField(FieldForm):
    link = TextField()

class LinksForm(FlaskForm):
    link_fields = FieldList(
        FormField(LinkField)
    )


# file form
class ExtFileField(FieldForm):
    file = FileField()
    filename = HiddenField()
    encrypted_filename = HiddenField()
    file_type = SelectField('File type', 
        choices=[('1',_l('Счёт фактура')),('2',_l('Не счёт фатура')),('3',_l('Что-то ещё'))])

class FilesForm(FlaskForm):
    file_fields = FieldList(
        FormField(ExtFileField)
    )


# picture form
class PictureField(FieldForm):
    picture = FileField()
    filename = HiddenField()
    encrypted_filename = HiddenField()

class PicturesForm(FlaskForm):
    picture_fields = FieldList(
        FormField(PictureField)
    )

def check_file_label(form, field):
    if (form.filename.data == "") and (not field.data):
        raise ValidationError(_l('Please choose a file'))



# number form
class NumberField(FieldForm):
    number = TextField()

class NumbersForm(FlaskForm):
    number_fields = FieldList(
        FormField(NumberField)
    )

def check_number(form, field):
    try:
        if field.data:
            float(field.data)
    except:
        raise ValidationError(_l('Not a number!'))


# Category form
class CategoryField_template(Form):
    category = TextField()

class CategoricalField(FieldForm):
    categories = FieldList(
        FormField(CategoryField_template)
    )

class CategoriesForm_template(FlaskForm):
    categories_fields = FieldList(
        FormField(CategoricalField)
    )


class CategoryField(FieldForm):
    categories = SelectField(label =_('Categories'), choices = [])

class CategoriesForm(FlaskForm):
    categories_fields = FieldList(
        FormField(CategoryField)
    )

app/tasks/forms.py
from flask_babel import _, lazy_gettext as _l
from flask_wtf import FlaskForm
from app.models import Users, Roles
from wtforms import TextField, SubmitField, SelectField
from wtforms_sqlalchemy.fields import QuerySelectField
from sqlalchemy import or_
from flask_login import current_user


def assigners_query():
    return Users.query.join(Users.roles).filter(or_(Roles.name == "Admin", 
        Roles.name == "Usual"), ~Users.roles.any(Roles.name == "God"))

def get_pk(obj):
    return str(obj)

def acceptors_query():
    return Users.query.join(Users.roles).filter(or_(Roles.name == "Client", 
        Roles.name == "Usual"), ~Users.roles.any(Roles.name == "God"), Users.id != current_user.id)

class TaskForm_edit(FlaskForm):
    assigner = QuerySelectField(_l('Assigner'), query_factory=assigners_query, 
        get_pk = get_pk, get_label = "email")
    acceptor = QuerySelectField(_l('Acceptor'), query_factory=acceptors_query, 
        get_pk = get_pk, get_label = "email")
    status = SelectField(_l('Status'), 
        choices=[('Issued',_l('Issued')),('In progress',_l('In progress')),('Done',_l('Done'))])
    submit = SubmitField(_l('Submit'))

class TaskForm_create(FlaskForm):
    acceptor = QuerySelectField(_l('Acceptor'), query_factory=acceptors_query, 
        get_pk = get_pk, get_label ="email")
    submit = SubmitField(_l('Submit'))

class TemplateForm(FlaskForm):
    name = TextField(label = _l("Template name"))
    submit = SubmitField(_l('Submit'))

app/users/forms.py
from flask_babel import _, lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError, DataRequired, Email
from app.models import Users
from wtforms import Form, StringField, SubmitField, SelectField
from flask_wtf.file import FileField, FileAllowed

class EditProfileForm_Admin(FlaskForm):
    email = StringField(_l('Email'), validators=[DataRequired(), Email()])
    role_list = SelectField(_l('Role'), 
        choices=[('Admin',_l('Admin')),('Usual',_l('Usual user')),('Not confirmed',_l('Not confirmed'))])
    picture = FileField(_l('Update Profile Picture'), validators=[FileAllowed(['jpg', 'png','jpeg'])])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_email, *args, **kwargs):
        super(EditProfileForm_Admin, self).__init__(*args, **kwargs)
        self.original_email = original_email

    def validate_email(self, email):
        if email.data != self.original_email:
            user = Users.query.filter_by(email=self.email.data).first()
            if user is not None:
                raise ValidationError(_l('Please use a different email.'))


class EditProfileForm(FlaskForm):
    picture = FileField(_l('Update Profile Picture'), validators=[FileAllowed(['jpg', 'png','jpeg'])])
    submit = SubmitField(_l('Submit'))

app/tasks/__init__.py
from flask import Blueprint

bp = Blueprint('tasks', __name__, template_folder='templates')

from app.tasks import routes

app/tasks/routes.py
# Здесь добавлены все функции, связанные с созданиемб редактированием и удалением заданий и шаблонов к ним

from flask import render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_required
from flask_babel import _, lazy_gettext as _l
from werkzeug.urls import url_parse

from app import db
from app.tasks import bp
from app.tasks.forms import *
from app.models import *
from app.dynamic_fields.dynamic_fields import *
from app.dynamic_fields.forms import AddFieldForm
from app.routes import roles_required


#_____________________________________________
#      Task_templates - Шаблоны заданий
#---------------------------------------------

def process_template(template, is_edit):
    form = TemplateForm()
    add_field_form = AddFieldForm()
    
    is_validated, dynamic_forms = dynamic_fields(template, template.fields, True)

    if request.method == 'GET':
        #Заполняем поля при отображении страницы
        form.name.data = template.name
        
    elif is_validated and form.validate_on_submit():
        # Сохраняем данные в БД
        template.name = form.name.data
        if not is_edit:        
            db.session.add(template) 
        db.session.commit()
        return redirect(url_for('tasks.task_templates'))

    return render_template("create_or_edit_task_template.html", add_field_form = add_field_form,
        form = form, is_template = True, dynamic_forms = dynamic_forms)

# Создание шаблона
@bp.route('/create_task_template', methods=['GET', 'POST'])
@roles_required(['Admin'])
def create_task_template():
    template = Task_templates()
    return process_template(template, False)


@bp.route('/edit_task_template/<template_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def edit_task_template(template_id):
    template = Task_templates.query.filter_by(id = template_id).first()
    return process_template(template, True)


@bp.route('/delete_task_template/<template_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def delete_task_template(template_id):
    template = Task_templates.query.filter_by(id = template_id).first()
    delete_fields(template.fields)
    db.session.commit()
    db.session.delete(template)
    db.session.commit()
    return redirect(url_for("tasks.task_templates"))


#_____________________________________________
#            Tasks - Задания
#---------------------------------------------

def process_task(form, task, fields, is_edit):
    #Формы для разных типов полей

    is_validated, dynamic_forms = dynamic_fields(task, fields, False)

    if request.method == 'GET' and is_edit:
        #Заполняем поля при отображении страницы
        form.status.data = task.status
        form.assigner.data = task.assigner
        form.acceptor.data = task.acceptor
 
    elif is_validated and form.validate_on_submit():
        if is_edit:
            assigner = form.assigner.data
        else:
            assigner = current_user

        task.assigner = assigner
        task.acceptor = form.acceptor.data

        if is_edit:
            task.status = form.status.data

        if not is_edit:
            db.session.add(task)    
        db.session.commit()
        flash(_l('Your changes have been saved.'))
        return redirect(url_for('auth.login'))
    
    return render_template("create_or_edit_task.html", form = form, 
        is_edit = is_edit, dynamic_forms = dynamic_forms, is_template = False)


@bp.route('/create_task/<template_id>', methods=['GET', 'POST'])
@roles_required(['Admin', 'Usual'])
def create_task(template_id):
    task = Tasks()
    fields = Task_templates.query.filter_by(id = template_id).first().fields
    form = TaskForm_create()

    return process_task(form, task, fields, False)

    
@bp.route('/edit_task/<task_id>', methods=['GET', 'POST'])
@roles_required(['Admin'])
def edit_task(task_id):
    task = Tasks.query.filter_by(id = task_id).first()
    form = TaskForm_edit()
    return process_task(form, task, task.fields, True)


@bp.route('/delete_task/<task_id>')
@roles_required(['Admin'])
def delete_task(task_id):
    task = Tasks.query.filter(Tasks.id == task_id).first()
    delete_fields(task.fields)
    db.session.commit()
    db.session.delete(task)
    db.session.commit()
    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('users.all_users')
    return redirect(next_page)



#_____________________________________________
#      Отображение заданий на страницах
#---------------------------------------------

@bp.route('/all_tasks', methods=['GET', 'POST'])
@roles_required(['Admin'])
def all_tasks():
    return render_template("tasks.html", title = _l("All tasks"),
        tasks = Tasks.query.order_by(Tasks.timestamp.desc()).all())


# Страница с выбором существующего шаблона задания или создание нового шаблона (создание только для админа)
@bp.route('/task_templates', methods=['GET', 'POST'])
@roles_required(['Admin', 'Usual'])
def task_templates():
    templates = Task_templates.query.all()
    return render_template('task_templates.html', templates = templates)


@bp.route('/issued_tasks', methods=['GET', 'POST'])
@roles_required(['Admin', 'Usual'])
def issued_tasks():
    tasks = current_user.assign.order_by(Tasks.timestamp.desc()).all()
    return render_template("tasks.html", title=_l('Issued tasks'), tasks = tasks)


@bp.route('/your_tasks', methods=['GET', 'POST'])
@login_required
def your_tasks():
    tasks = current_user.accept.order_by(Tasks.timestamp.desc()).all()
    return render_template("tasks.html", title=_l('My tasks'), tasks = tasks)

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__, template_folder='templates')

from app.users import routes

app/users/routes.py
from flask_babel import _, lazy_gettext as _l
from flask import render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_required
from flask import abort

from werkzeug.urls import url_parse
from sqlalchemy import or_
import os
from PIL import Image
from flask_wtf import FlaskForm

from app.routes import roles_required

from app import app, db
from app.users import bp
from app.users.forms import *
from app.models import *



# Главная страница пользователя, с заданиями, которые он выдал
@bp.route('/user/<id>', methods=['GET', 'POST'])
@login_required
def user(id):
    user = Users.query.filter_by(id=id).first_or_404()
    user_roles = [role.name for role in user.roles]
    if "God" in user_roles and current_user.id != user.id:
        return abort(404)
    tasks = Tasks.query.filter(or_(Tasks.assigner_id == user.id, 
        Tasks.acceptor_id == user.id)).order_by(Tasks.timestamp.desc()).all()
    return render_template('user.html', title = user.last_name+" "+ user.first_name, 
        user=user, tasks = tasks)


@bp.route('/all_users', methods=['GET', 'POST'])
@roles_required(['Admin'])
def all_users():
    all_users = Users.query.filter(Users.id!=current_user.id, ~Users.roles.any(Roles.name == "God")).all()
    return render_template("all_users.html", title = _l("All users"), users = all_users)


def save_avatar(user, picture):
    if picture:
        __ , encrypted_filename = encode_filename(picture.filename)
        image = Image.open(picture)
        image.save(os.path.join(app.root_path, 'static/avatars/', encrypted_filename))
        user.avatar_path = encrypted_filename


@bp.route('/edit_user/<id>', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    is_admin = (current_user.roles[0].name == "Admin")
    user = Users.query.filter_by(id=id).first()
    
    if not is_admin and current_user.id != user.id:
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('users.all_users')
        return redirect(next_page)

    if is_admin:
        form = EditProfileForm_Admin(user.email)
    else:
        form = EditProfileForm()

    if user.profile:
        profile = user.profile
        fields = profile.fields
    else:
        profile = Profiles()

        profile_template = Profile_template.query.filter_by(id=1).first()
        fields = []
        if profile_template:
            fields = profile_template.fields

    is_validated, dynamic_forms = dynamic_fields(profile, fields, True)

    if request.method == 'GET' and is_admin:
        # Предзаполнение полей
        form.email.data = user.email
        form.role_list.data = user.roles[0].name

    elif is_validated and form.validate_on_submit():
        save_avatar(user, form.picture.data)
        if is_admin:
            user.email = form.email.data
            user.roles[0].name = form.role_list.data
            
        if not user.profile:
            user.profile = profile
            db.session.add(profile)
        db.session.commit()
        flash(_l('Your changes have been saved.'))
        return redirect(url_for("users.all_users"))

    
    return render_template('edit_user.html', title=_l('Edit Profile'),
        form=form, user = user, is_template = False, dynamic_forms = dynamic_forms)


# --- Удаление пользователя и заданий ----
@bp.route('/delete_user/<user_id>')
@roles_required(['Admin'])
def delete_user(user_id):
    user = Users.query.filter_by(id=user_id).first()

    # Удаление аватарки
    if user.avatar_path:
        os.remove(os.path.join(app.root_path, 'static/avatars/', user.avatar_path))

    # #Удаления информации о профиле
    if user.profile:
        if user.profile.fields:
            delete_fields(user.profile.fields)
        db.session.delete(user.profile)
        
    db.session.commit()

    #Удаление всех заданий, связанных с этим пользователем
    acceptor_tasks = Tasks.query.filter(Tasks.acceptor_id == user.id).all()
    assigner_tasks = Tasks.query.filter(Tasks.assigner_id == user.id).all()
    for task in acceptor_tasks:
        delete_task(task.id)
    for task in assigner_tasks:
        delete_task(task.id)

    db.session.commit()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("users.all_users"))

@bp.route('/confirm_user/<id>')
@roles_required(['Admin'])
def confirm_user(id):
    user = Users.query.filter_by(id=id).first()
    user.roles[0].name = "Usual"
    db.session.commit()
    return redirect(url_for("users.all_users"))


@bp.route('/profile_template',methods=['GET', 'POST'])
@roles_required(['Admin'])
def profile_template():

    class TemplateProfileForm(FlaskForm):
        submit = SubmitField(_l('Submit'))

    template = Profile_template.query.filter_by(id=1).first()
    if template==None:
        template = Profile_template(id = 1)
        db.session.add(template)

    form = TemplateProfileForm()
    add_field_form = AddFieldForm()
    
    is_validated, dynamic_forms = dynamic_fields(template, template.fields, True)

    if is_validated:
        profiles = Profiles.query.all()
        for profile in profiles:
            delete_fields(profile.fields)
        db.session.commit()
        Profiles.query.delete()
        db.session.commit()
        return redirect(url_for("toolbar_settings"))


    return render_template("profile_template.html", add_field_form = add_field_form, 
        form = form, is_template = True, dynamic_forms = dynamic_forms)

# delete_task нужен в delete_user
from app.tasks.routes import delete_task
from app.dynamic_fields.dynamic_fields import *

app/templates/_task.html
<div style="display: flex; flex-direction: column;" id="task_full">
	{% for field in task.fields %}
		{% if field.display %}
			<div style="order: {{field.order}}" id="task">
					<div class="label">
							{{field.label}}
					</div>
					<div class="info">
						{% if field.media.text %}
							{% if is_link(field.media.text) %}
								<a href="{{ append_http(field.media.text) }}">
									{{ field.media.text }}
								</a>
							{% else %}
								{{ field.media.text }}
							{% endif %}
						{% elif field.media.textArea %}
							{{ field.media.textArea }}
						{% elif field.media.date %}
							{{ field.media.date.strftime('%d %B %Y') }}
						{% elif field.media.filename %}
								<a href="{{ url_for('download_file', filename = field.media.encrypted_filename) }}">
									<b>{{ field.media.filename }}</b>
								</a>
						{% elif field.media.picture %}
								<img src="{{ url_for('static',filename = 'files/' + field.media.encrypted_filename) }}" width="200" height="200">
						{% elif field.media.link %}
								<a href="{{ append_http(field.media.link) }}">
									{{ field.media.link }}
								</a>
						{% endif %}
					</div>
					
			</div>
		{% endif %}	
	{% endfor %}
</div>

<div class="task_info">

		<div class="avatar">
				<img src="{{ task.assigner.avatar() }}">
		</div>
		
		<div class="user_name">
				<a href="{{ url_for('user', id=task.assigner.id) }}">{{ task.assigner.email }}</a> | {{ _('Assigned to:')}} <a href="{{ url_for('user', id=task.acceptor.id) }}">{{ task.acceptor.email }}</a>
		</div>
		
		<div class="task_status">
				<div class="label">
						{{ _('Status:')}}
				</div>
				<div class="info">
						{{ _(task.status)}}
				</div>
		</div>

		<div class="task_issuid_time">
				<div class="label">
						{{ _('Issued time:')}}
				</div>
				<div class="info">
						{{ task.timestamp.strftime('%d %B %Y at %H:%M') }}
				</div>
		</div>
							
		<div class="user_edit">
				{% if current_user.roles[0].name == "Admin" %}
				<div class="edit">
						<a href="{{ url_for('edit_task', task_id=task.id) }}">{{ _('Edit')}}</a>
				</div>
				<div class="delete">
						<a href="{{ url_for('delete_task', task_id=task.id, next = request.path) }}">{{ _('Delete task')}}</a>	
				</div>
				{% endif %}  
		</div>

</div>

app/templates/all_users.html
{% extends "base.html" %}

{% block content %}

	{% for user in users %}
	
			<div id="user">
		
				<div class="avatar">
						<img src="{{ user.avatar() }}">
				</div>
				
				<div class="user_info">
				
						<div class="real_name">
								<div class="label">
										{{_("Full name")}}:
								</div>
								<div class="info">
										{{user.last_name}} {{user.first_name}}
								</div>
						</div>
				
						<div class="user_name">
								<div class="label">
										{{_('Email')}}:
								</div>
								<div class="info">
										<a href="{{ url_for('user', id=user.id) }}">{{ user.email }}</a>
								</div>
						</div>
						
						{% if user.roles %}
							<div class="user_role">
									<div class="label">
											{{ _('Role')}}:
									</div>
									<div class="info">
											{{_(user.roles[0].name)}}
									</div>
							</div>	
						{% endif %}
						{% if user.roles[0].name == 'Not confirmed' %}
						<div class="user_edit">
							<div class="edit">
									<a href="{{ url_for('confirm_user', id=user.id) }}">{{ _('Confirm')}}</a>
							</div>	
						</div>
						{% else %}
							<div class="user_edit">
									<div class="edit">
											<a href="{{ url_for('edit_user', id=user.id) }}">{{ _('Edit')}}</a>
									</div>
									<div class="delete">
											<a href="{{ url_for('delete_user', user_id=user.id) }}">{{ _('Delete user')}}</a>
									</div>
							</div>
						{% endif %}
				
				</div>				
			
			</div>
			

		
	{% endfor %}

    
{% endblock %}

app/templates/base.html
<html>
    <head>
	<link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

	<script src="https://use.fontawesome.com/fc5a4d0310.js"></script>
	{{ moment.include_jquery() }}
	{{ moment.include_moment() }}
	{{ moment.lang(g.locale) }}
	
        {% if title %}
        <title>{{ title }}</title>
        {% else %}
        <title>{{ _('Task manager')}}</title>
        {% endif %}
    </head>
    <body>
	
	<header>
		<h1>{{ title }}</h1>
		<div class="menu">
			<ul>
				<li>{{ moment(now()).format('HH:mm') }}</li>
				{% if current_user.is_anonymous %}
					<li><a href="{{ url_for('auth.login') }}"><i class="fa fa-chevron-right" aria-hidden="true"></i> {{ _('Sign in')}}</a></li>
				{% else %}
					<li><a href="{{ url_for('users.user', id=current_user.id) }}"><i class="fa fa-user-circle" aria-hidden="true"></i>  							{{current_user.real_name}}</a></li>
					<li><a href="{{ url_for('toolbar_settings') }}"><i class="fa fa-cogs" aria-hidden="true"></i> {{ _('Settings')}}</a></li>
					<li><a href="{{ url_for('auth.logout') }}"><i class="fa fa-power-off" aria-hidden="true"></i> {{ _('Logout')}}</a></li>
					{% endif %}

					<li>
						{% for language in LANGUAGES %}
							<a style = "float: right;" href="{{ url_for('change_language', language = language)}}">
								{{language}}
							</a>
						{% endfor %}				
					</li>			
			</ul>
		</div>
	</header>
	
	<div id="left">
	
		<div class="logo">
			<a href="#"><img src="{{ url_for('static', filename='logo/'+logo()) }}"></a>
		</div>
	
		<div class="nav">
			{% if not current_user.is_anonymous %}
				<ul>	
						{% if current_user.roles %}
							<li><a href="{{ url_for('sections.main') }}">{{ _('Main') }}</a></li>

							{% for section in get_sections() %}
								<li><a href="{{ url_for('sections.view_section', section_id=section.id) }}">{{ section.name }}</a></li>
							{% endfor %}
							<li><a href="{{ url_for('sections.all_documents') }}">{{ _('Documents') }}</a></li>

							{% if current_user.roles[0].name == "Admin" %}
								<li><a href="{{ url_for('users.all_users') }}">{{ _('All users')}}</a></li>
								<li><a href="{{ url_for('tasks.all_tasks') }}">{{ _('All tasks')}}</a></li>
								<li><a href="{{ url_for('tasks.task_templates') }}">{{ _('Create task')}}</a></li>
								
								<li><a href="{{ url_for('tasks.your_tasks') }}">{{ _('My tasks')}}</a></li>
								<li><a href="{{ url_for('tasks.issued_tasks') }}">{{ _('Issued tasks')}}</a></li>
								
								
							{% elif current_user.roles[0].name == "Usual" %}
								<li><a href="{{ url_for('tasks.task_templates') }}">{{ _('Create task')}}</a></li>
								<li><a href="{{ url_for('tasks.your_tasks') }}">{{ _('My tasks')}}</a></li>
								<li><a href="{{ url_for('tasks.issued_tasks') }}">{{ _('Issued tasks')}}</a></li>
								
								
							{% elif current_user.roles[0].name == "Client" %}
								<li><a href="{{ url_for('tasks.your_tasks') }}">{{ _('My tasks')}}</a></li>
							{% endif %}
							
							{% for link in current_user.extra_menu_fields %}
								<li><a href="{{ link.link }}">
									{% if link.name %}
											{{ _(link.name) }}
										{% else %}
										{{ _('Link')}}_{{link.id}}
										{% endif %}
									</a></li>
							{% endfor %}
							
								<li><a href="{{ url_for('add_extra_menu_field', name = title, next = request.path) }}">
										{{ _('Add')}}
								</a></li>
						{% endif %}
				</ul>
			{% endif %}
		</div>	
	</div>
	
	<div id="body">

        {% with messages = get_flashed_messages() %}
		{% if messages %}
		<ul>
		    {% for message in messages %}
		    <li>{{ message }}</li>
		    {% endfor %}
		</ul>
		{% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
		
	</div>
		
    </body>
</html>

app/templates/change_logo.html
{% extends "base.html" %}

{% block content %}
	<form action="" method="post" enctype="multipart/form-data">
		{{ form.hidden_tag() }}
		<p> 
			{{ form.file.label }}
			{{ form.file() }}
		</p>
		{% for error in form.file.errors %}
			<span style="color: red;">[{{ error }}]</span>
		{% endfor %}
		<p> {{ form.submit() }}
	</form>
{% endblock %}

app/templates/rename_link.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
	{{ form.hidden_tag() }}
	<p> 
		{{ form.name.label }}
		{{ form.name() }}
	</p>
	<p> {{ form.submit() }}
</form>


{% endblock %}

app/templates/section_pages.html
{% extends "base.html" %}

{% block content %}

<div class="task_info">

	<div class="user_edit">
		<div class="edit">
				<a href="{{ url_for('create_page', section_id=section_id) }}">{{ _('Create new page')}}</a>
		</div> 
	</div>
</div>      


    {% for page in pages %}
    		{% include 'page.html' %}
    		<br>
    {% endfor %}

{% endblock %}

app/templates/toolbar_settings.html
{% extends "base.html" %}

{% block content %}

<div>
	<a href="{{ url_for('users.profile_template') }}">{{_('Profile template')}}</a>
</div>
<div>
	<p>... </p> 
</div>
<div>
		<a href="{{ url_for('sections.create_section') }}">{{_('Create section')}}</a>
</div>
<div>
		<a href="{{ url_for('change_logo') }}">{{ _('Change logo')}}</a>
</div>
<div>
	<p>... </p> 
</div>


{% for section in get_sections() %}

	<div class="user_edit">
		<div class="edit" >
			<a href="{{ url_for('sections.view_section', section_id=section.id) }}">{{ section.name }}</a>
		</div>
		<div class="edit">
			<a href="{{ url_for('sections.edit_section', section_id=section.id) }}">{{ _('Edit section') }}</a>
		</div>
		<div class="delete">
			<a href="{{ url_for('sections.delete_section', section_id=section.id) }}">{{_('Delete section')}}</a>	
		</div>
	</div>

{% endfor %}



{% for link in current_user.extra_menu_fields %}
	<div>
		<a style = "margin-right: 50px; " href="{{ link.link }}">
			{% if link.name %}
				{{ link.name }}
			{% else %}
				{{ _('Link')}}_{{link.id}}
			{% endif %}
		</a>
		<a style = "margin-right: 50px; " href="{{ url_for('rename_menu_field', link_id = link.id) }}">{{ _('Rename link')}}</a>
		<a style = "margin-right: 50px; " href="{{ url_for('delete_menu_field', link_id = link.id) }}">{{ _('Delete link')}}</a>
	</div>
{% endfor %}


{% endblock %}